# SciPy

SciPy is a collection of mathematical algorithms and convenience functions built on the Numpy extension of Python. It adds significant power to the interactive Python session by providing the user with high-level commands and classes for manipulating and visualizing data. With SciPy an interactive Python session becomes a data-processing and system-prototyping environment rivaling systems such as MATLAB, IDL, Octave, R-Lab, and SciLab.

The additional benefit of basing SciPy on Python is that this also makes a powerful programming language available for use in developing sophisticated programs and specialized applications. Scientific applications using SciPy benefit from the development of additional modules in numerous niches of the software landscape by developers across the world. 

Everything from parallel programming to web and data-base subroutines and classes have been made available to the Python programmer. All of this power is available in addition to the mathematical libraries in SciPy.

We'll focus a lot more on NumPy arrays, but let's show some of the capabilities of SciPy:

In [1]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,8]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 8]]


## Linear Algebra
**linalg**

In [2]:
from scipy import linalg

Determinant of a Matrix

In [3]:
# Compute the determinant of a matrix
linalg.det(A)

2.999999999999997

Compute pivoted LU decomposition of a matrix.

The decomposition is::

    A = P L U

where P is a permutation matrix, L lower triangular with unit
diagonal elements, and U upper triangular.

In [4]:
P, L, U = linalg.lu(A)

In [5]:
P

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [6]:
L

array([[1.        , 0.        , 0.        ],
       [0.14285714, 1.        , 0.        ],
       [0.57142857, 0.5       , 1.        ]])

In [7]:
U

array([[7.        , 8.        , 8.        ],
       [0.        , 0.85714286, 1.85714286],
       [0.        , 0.        , 0.5       ]])

In [8]:
np.dot(L,U)

array([[7., 8., 8.],
       [1., 2., 3.],
       [4., 5., 6.]])

We can find out the eigenvalues and eigenvectors of this matrix:

In [9]:
EW, EV = linalg.eig(A)

In [10]:
EW

array([15.55528261+0.j, -1.41940876+0.j, -0.13587385+0.j])

In [11]:
EV

array([[-0.24043423, -0.67468642,  0.51853459],
       [-0.54694322, -0.23391616, -0.78895962],
       [-0.80190056,  0.70005819,  0.32964312]])

Solving systems of linear equations can also be done:

In [12]:
v = np.array([[2],[3],[5]])

In [13]:
v

array([[2],
       [3],
       [5]])

In [14]:
s = linalg.solve(A,v)

In [15]:
s

array([[-2.33333333],
       [ 3.66666667],
       [-1.        ]])

## Sparse Linear Algebra
SciPy has some routines for computing with sparse and potentially very large matrices. The necessary tools are in the submodule scipy.sparse.

We make one example on how to construct a large matrix:

In [16]:
from scipy import sparse

In [17]:
# Row-based linked list sparse matrix
A = sparse.lil_matrix((1000, 1000))

In [18]:
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in LInked List format>

In [19]:
A[0,:100] = np.random.rand(100)

In [20]:
A[1,100:200] = A[0,:100]

In [21]:
A.setdiag(np.random.rand(1000))

In [22]:
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1199 stored elements in LInked List format>

**Linear Algebra for Sparse Matrices**

In [23]:
from scipy.sparse import linalg

In [24]:
# Convert this matrix to Compressed Sparse Row format.
A.tocsr()

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1199 stored elements in Compressed Sparse Row format>

In [25]:
A = A.tocsr()

In [26]:
b = np.random.rand(1000)

In [27]:
linalg.spsolve(A, b)

array([ 7.72798788e+05, -7.92617169e+03,  4.64489778e+00,  9.73522128e-01,
        1.29193072e+00,  1.19670691e+00,  8.94022799e-01,  1.43576471e-01,
        2.17477116e-01,  6.76283480e-01,  3.46629423e-01,  7.41760722e-01,
        9.81000398e-01,  1.23447841e+00,  1.83835693e-02,  1.12405854e+00,
        2.33696576e-01,  1.18807732e+00,  9.22592083e-01,  2.22676693e+00,
        1.10963758e+00,  4.23829437e+00,  1.27635187e+00,  5.85529193e+00,
        5.20942052e-01,  1.00329319e+00,  2.81155017e-01,  4.32179479e-01,
        4.76391413e+00,  1.32874491e+00,  1.72149397e+00,  7.25107533e-01,
        1.71185811e-01,  8.05463769e-01,  3.21002489e+00,  8.26512217e-02,
        1.05133282e-01,  1.64795457e+00,  6.72076802e-01,  2.93581362e-01,
        8.37931428e-01,  1.55878641e+00,  8.58013743e+00,  2.46005553e+00,
        6.53536732e-01,  1.01189117e+00,  1.45390390e+00,  1.43589032e+00,
        2.39124754e-01,  4.88352428e-01,  1.41507118e+00,  2.42731300e+00,
        3.02521966e+00,  

There is a lot more that SciPy is capable of, such as Fourier Transforms, Bessel Functions, etc...

You can reference the Documentation for more details!

## Linear algebra Revisiting....

The Linear Algebra module of NumPy offers various methods to apply linear algebra on any numpy array.
You can find:
1. rank, determinant, trace, etc. of an array.
2. eigen values of matrices.
3. matrix and vector products (dot, inner, outer,etc. product), matrix exponentiation.
4. solve linear or tensor equations and much more!.


Consider the example below which explains how we can use NumPy to do some matrix operations.

In [28]:
import numpy as np
 
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
 
print("Rank of A:", np.linalg.matrix_rank(A))
 
print("\nTrace of A:", np.trace(A))
 
print("\nDeterminant of A:", np.linalg.det(A))
 
print("\nInverse of A:\n", np.linalg.inv(A))
 
print("\nMatrix A raised to power 3:\n", np.linalg.matrix_power(A, 3))


Rank of A: 3

Trace of A: 11

Determinant of A: -306.0

Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Matrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]


## Solving Equations 

Let us assume that we want to solve this linear equation set:

1.   x + 2y = 8

2.   3*x + 4*y = 18

This problem can be solved using linalg.solve method as shown in example below:

In [29]:
# coefficients
a = np.array([[1, 2], [3, 4]])
# constants
b = np.array([8, 18])
 
print("Solution of linear equations:", np.linalg.solve(a, b))


Solution of linear equations: [2. 3.]


NumPy is a widely used general purpose library which is at the core of many other computation libraries like scipy, scikit-learn, tensorflow, matplotlib, opencv, etc. Having a basic understanding of NumPy helps in dealing with other higher level libraries efficiently!